# Generated by Django 2.1.1 on 2018-12-15 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rundeck', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='use_chatbot',
            field=models.BooleanField(default=False),
        ),
    ]
